Updated installer to v0.1.2: Fixing linter issues
- Fix shellcheck linter warnings.
- [WIP] Update script.

Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,20 +1,25 @@
 #!/usr/bin/env bash
 
 # This script has been tested on the following systems:
-# - GNU bash v5.1.16 on Linux Mint 21 "Vanessa"
+# - GNU bash v5.1.16 on Linux Mint 21
+# - GNU bash v5.1.16 on Kali Linux Rolling
 
 # ? Set variables.
-name="Neovim Config"
-version=(0 1 1)
-title="${name} v${version[@]:0:1}.${version[@]:1:1}.${version[@]:2:1}"
+name="Neovim Config Installer"
+version=(0 1 2)
+title="${name} v${version[*]:0:1}.${version[*]:1:1}.${version[*]:2:1}"
 
-target_branch="main"  # The branch to which the configs will be pulled from.
+target_branch="nvim-ufo"  # The branch to which the configs will be pulled from.
 installation_files="${PWD}/neovim-init"
 nvim_config_path="${HOME}/.config/nvim"
 nvim_data_path="${HOME}/.local/share/nvim"
 packer_installation_path="${nvim_data_path}/site/pack/packer/start/packer.nvim"
 plugins_installed_flag_file="${nvim_data_path}/.plugins_installed"
 min_nvim_version=(0 7 2)  # Minimum Neovim version required.
+
+echo
+echo "$title"
+echo
 
 # ? Check requirements.
 echo "Checking requirements..."
@@ -39,23 +44,23 @@ if ! [[ -x "$(command -v nvim)" ]]; then  # Check if Neovim is installed.
 else  # If Neovim is installed, check its version.
     echo "Neovim is installed. Checking its version..."
     nvim_version=$(nvim -v)
-    nvim_version=${nvim_version[@]:5:6}  # Get the version of Neovim using `nvim -v` in format `vX.X.X`.
+    nvim_version=${nvim_version[*]:5:6}  # Get the version of Neovim using `nvim -v` in format `vX.X.X`.
     echo "Detected Neovim version: ${nvim_version}"
 
-    upgrade_prompt="Neovim ${nvim_version} is not supported.\nPlease upgrade to at least v${min_nvim_version[@]:0:1}.${min_nvim_version[@]:1:1}.${min_nvim_version[@]:2:1} or higher and try again.\n"
+    upgrade_prompt="Neovim ${nvim_version} is not supported.\nPlease upgrade to at least v${min_nvim_version[*]:0:1}.${min_nvim_version[*]:1:1}.${min_nvim_version[*]:2:1} or higher and try again.\n"
     # The if-else nest below will check if the user's Neovim version is supported.
-    if [[ ${nvim_version:1:1} -lt ${min_nvim_version[@]:0:1} ]]; then  # Check major version.
-        printf "$upgrade_prompt"
+    if [[ ${nvim_version:1:1} -lt ${min_nvim_version[*]:0:1} ]]; then  # Check major version.
+        printf "%s" "$upgrade_prompt"
         exit 3
 
     else
-        if [[ ${nvim_version:3:1} -lt ${min_nvim_version[@]:1:1} ]]; then  # Check minor version.
-            printf "$upgrade_prompt"
+        if [[ ${nvim_version:3:1} -lt ${min_nvim_version[*]:1:1} ]]; then  # Check minor version.
+            printf "%s" "$upgrade_prompt"
             exit 4
 
         else
-            if [[ ${nvim_version:5:1} -lt ${min_nvim_version[@]:2:1} ]]; then  # Check patch/hotfix version.
-                printf "$upgrade_prompt"
+            if [[ ${nvim_version:5:1} -lt ${min_nvim_version[*]:2:1} ]]; then  # Check patch/hotfix version.
+                printf "%s" "$upgrade_prompt"
                 exit 5
             fi
         fi
@@ -73,10 +78,10 @@ echo "This will overwrite existing files in the said directory."
 echo
 while true; do
     printf "Are you sure? (Y/n) > "
-    read installation_confirmation
+    read -r installation_confirmation
 
     if [[ "${installation_confirmation}" == "" || "${installation_confirmation}" =~ ^[y|Y].* ]]; then
-        printf "Installing ${title} customization files...\n"
+        printf "Installing %s customization files...\n" "${title}"
         break
 
     elif [[ "${installation_confirmation}" =~ ^[n|N].* ]]; then
@@ -94,9 +99,9 @@ done
 echo
 
 if [[ -e "${nvim_config_path}" ]]; then
-    printf "Removing existing files in \`${nvim_config_path}\`...\r"
+    printf "Removing existing files in \`%s\`...\r" "${nvim_config_path}"
     rm -r -- "${nvim_config_path}"  # Delete the existing Neovim configuration directory.
-    printf "Removing existing files in \`${nvim_config_path}\`... Done!\n"
+    printf "Removing existing files in \`%s\`... Done!\n" "${nvim_config_path}"
 
 else
     echo "No existing files found in \`${nvim_config_path}\`."
@@ -104,9 +109,9 @@ else
 fi
 
 if [[ -e "${packer_installation_path}" ]]; then
-    printf "Removing existing files in \`${packer_installation_path}\`...\r"
+    printf "Removing existing files in \`%s\`...\r" "${packer_installation_path}"
     rm -rf -- "${packer_installation_path}"
-    printf "Removing existing files in \`${packer_installation_path}\`... Done!\n"
+    printf "Removing existing files in \`%s\`... Done!\n" "${packer_installation_path}"
 
 else
     echo "No existing files found in \`${packer_installation_path}\`."
@@ -114,9 +119,9 @@ else
 fi
 
 if [[ -e "$plugins_installed_flag_file" ]]; then
-    printf "Removing flag file in \`${plugins_installed_flag_file}\`...\r"
+    printf "Removing flag file in \`%s\`...\r" "${plugins_installed_flag_file}"
     rm -- "${plugins_installed_flag_file}"
-    printf "Removing flag file in \`${plugins_installed_flag_file}\`... Done!\n"
+    printf "Removing flag file in \`%s\`... Done!\n" "${plugins_installed_flag_file}"
 
 else
     echo "No flag file found in \`${plugins_installed_flag_file}\`."
@@ -129,52 +134,46 @@ echo
 
 # Check if the installation files exist.
 if [[ -d "$installation_files" ]]; then
-    printf "Copying customization files to \`${nvim_config_path}\`...\r"
-    cp -r "$installation_files" "$nvim_config_path"  # Copy the customization files to the Neovim configuration directory.
-    if [[ $? -eq 0 ]]; then
-        printf "Copying customization files to \`${nvim_config_path}\`... Done!\n"
+    printf "Copying customization files to \`%s\`...\r" "${nvim_config_path}"
+    if ! cp -r "$installation_files" "$nvim_config_path"; then  # Copy the customization files to the Neovim configuration directory.
+        printf "Copying customization files to \`%s\`... Done!\n" "${nvim_config_path}"
         echo "Please run \`nvim\` to finish the installation."
         exit 0
 
     else
-        printf "Copying customization files to \`${nvim_config_path}\`... Failed!\n"
+        printf "Copying customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 7
     fi
 
 else
-    printf "Downloading customization files to \`${nvim_config_path}\`...\r"
+    printf "Downloading customization files to \`%s\`...\r" "${nvim_config_path}"
     mkdir -p "${nvim_config_path}/lua"  # Create the Neovim configuration directory.
-    curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/init.lua" -o "${nvim_config_path}/init.lua"
-    if [[ $? -ne 0 ]]; then
-        printf "Downloading customization files to \`${nvim_config_path}\`... Failed!\n"
+    if ! curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/init.lua" -o "${nvim_config_path}/init.lua"; then
+        printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 8
     fi
 
-    curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/keymaps.lua" -o "${nvim_config_path}/lua/keymaps.lua"
-    if [[ $? -ne 0 ]]; then
-        printf "Downloading customization files to \`${nvim_config_path}\`... Failed!\n"
+    if ! curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/keymaps.lua" -o "${nvim_config_path}/lua/keymaps.lua"; then
+        printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 9
     fi
 
-    curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/options.lua" -o "${nvim_config_path}/lua/options.lua"
-    if [[ $? -ne 0 ]]; then
-        printf "Downloading customization files to \`${nvim_config_path}\`... Failed!\n"
+    if ! curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/options.lua" -o "${nvim_config_path}/lua/options.lua"; then
+        printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 10
     fi
 
-    curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/plugins.lua" -o "${nvim_config_path}/lua/plugins.lua"
-    if [[ $? -ne 0 ]]; then
-        printf "Downloading customization files to \`${nvim_config_path}\`... Failed!\n"
+    if ! curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/plugins.lua" -o "${nvim_config_path}/lua/plugins.lua"; then
+        printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 11
     fi
 
-    curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/vars.lua" -o "${nvim_config_path}/lua/vars.lua"
-    if [[ $? -ne 0 ]]; then
-        printf "Downloading customization files to \`${nvim_config_path}\`... Failed!\n"
+    if ! curl -sSfL "https://raw.githubusercontent.com/SetupGuides/Neovim/${target_branch}/neovim-init/lua/vars.lua" -o "${nvim_config_path}/lua/vars.lua"; then
+        printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
         exit 12
     fi
 
-    printf "Downloading customization files to \`${nvim_config_path}\`... Done!\n"
+    printf "Downloading customization files to \`%s\`... Done!\n" "${nvim_config_path}"
     echo "Please run \`nvim\` to finish the installation."
     exit 0
 fi
