[WIP] Update config instead of re-install
Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,7 +6,7 @@
 
 # ? Set variables.
 name="Neovim Config Installer"
-version=(0 1 2)
+version=(0 2 0)
 title="${name} v${version[*]:0:1}.${version[*]:1:1}.${version[*]:2:1}"
 
 target_branch="nvim-ufo"  # The branch to which the configs will be pulled from.
@@ -16,6 +16,14 @@ nvim_data_path="${HOME}/.local/share/nvim"
 packer_installation_path="${nvim_data_path}/site/pack/packer/start/packer.nvim"
 plugins_installed_flag_file="${nvim_data_path}/.plugins_installed"
 min_nvim_version=(0 7 2)  # Minimum Neovim version required.
+
+if [[ "$1" = "--reinstall" ]]; then
+    force_reinstall=true
+
+else
+    force_reinstall=false
+
+fi
 
 echo
 echo "$title"
@@ -67,12 +75,28 @@ else  # If Neovim is installed, check its version.
     fi
 fi
 
+# Check what to do.
+if [[ -e "${nvim_config_path}" ]] && ! $force_reinstall; then
+    config_perform="update"
+
+else
+    config_perform="install"
+fi
+
+if [[ -e "${packer_installation_path}" ]] && ! $force_reinstall; then
+    packer_perform="update"
+
+else
+    packer_perform="install"
+
+fi
+
 # ? Ask for user confirmation.
 echo
-echo "This will install the following:"
+echo "This will perform the following:"
 echo
-echo "- ${name} on \`${nvim_config_path}\`."
-echo "- packer.nvim on \`${packer_installation_path}\`."
+echo "- ${config_perform} ${name} on \`${nvim_config_path}\`."
+echo "- ${packer_perform} packer.nvim on \`${packer_installation_path}\`."
 echo
 echo "This will overwrite existing files in the said directory."
 echo
@@ -98,24 +122,28 @@ done
 # ? Install the customization files.
 echo
 
-if [[ -e "${nvim_config_path}" ]]; then
-    printf "Removing existing files in \`%s\`...\r" "${nvim_config_path}"
-    rm -r -- "${nvim_config_path}"  # Delete the existing Neovim configuration directory.
-    printf "Removing existing files in \`%s\`... Done!\n" "${nvim_config_path}"
+if [[ "${config_perform}" = "install" ]]; then
+    if [[ -e "${nvim_config_path}" ]]; then
+        printf "Removing existing files in \`%s\`...\r" "${nvim_config_path}"
+        rm -r -- "${nvim_config_path}"  # Delete the existing Neovim configuration directory.
+        printf "Removing existing files in \`%s\`... Done!\n" "${nvim_config_path}"
 
-else
-    echo "No existing files found in \`${nvim_config_path}\`."
+    else
+        echo "No existing files found in \`${nvim_config_path}\`."
 
+    fi
 fi
 
-if [[ -e "${packer_installation_path}" ]]; then
-    printf "Removing existing files in \`%s\`...\r" "${packer_installation_path}"
-    rm -rf -- "${packer_installation_path}"
-    printf "Removing existing files in \`%s\`... Done!\n" "${packer_installation_path}"
+if [[ "${packer_installation_path}" = "update" ]]; then
+    if [[ -e "${packer_installation_path}" ]]; then
+        printf "Removing existing files in \`%s\`...\r" "${packer_installation_path}"
+        rm -rf -- "${packer_installation_path}"
+        printf "Removing existing files in \`%s\`... Done!\n" "${packer_installation_path}"
 
-else
-    echo "No existing files found in \`${packer_installation_path}\`."
+    else
+        echo "No existing files found in \`${packer_installation_path}\`."
 
+    fi
 fi
 
 if [[ -e "$plugins_installed_flag_file" ]]; then
@@ -129,13 +157,27 @@ else
 fi
 
 echo
-git clone --depth=1 "https://github.com/wbthomason/packer.nvim.git" "${packer_installation_path}"
+if [[ "${packer_perform}" = "install" ]]; then
+    if ! git clone --depth=1 "https://github.com/wbthomason/packer.nvim.git" "${packer_installation_path}"; then
+        echo "Failed to clone packer.nvim"
+        exit 13
+
+    fi
+
+else
+    if ! cd "${packer_installation_path}" && git pull && cd -; then
+        echo "Git pull failed."
+        exit 14
+
+    fi
+
+fi
 echo
 
 # Check if the installation files exist.
 if [[ -d "$installation_files" ]]; then
     printf "Copying customization files to \`%s\`...\r" "${nvim_config_path}"
-    if ! cp -r "$installation_files" "$nvim_config_path"; then  # Copy the customization files to the Neovim configuration directory.
+    if cp -r "$installation_files" "$nvim_config_path"; then  # Copy the customization files to the Neovim configuration directory.
         printf "Copying customization files to \`%s\`... Done!\n" "${nvim_config_path}"
         echo "Please run \`nvim\` to finish the installation."
         exit 0
