Updated installer.
Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,7 +7,7 @@
 
 # ? Set variables.
 name="Neovim Config Installer"
-version=(0 8 0)  # Installer version; different from config version and Neovim version.
+version=(0 9 0)  # Installer version; different from config version and Neovim version.
 title="${name} v${version[*]:0:1}.${version[*]:1:1}.${version[*]:2:1}"
 
 target_branch="rewrite"  # The branch to which the configs will be pulled from.
@@ -240,17 +240,15 @@ if [[ -d "$installation_files" ]]; then
 
 else
     echo "Downloading file list..."
-    files_to_download=$(curl "${filelist_url}")
+    files_to_download=$(curl -sSfL "${filelist_url}")
     printf "Downloading customization files to \`%s\`...\r" "${nvim_config_path}"
     for file in ${files_to_download}; do
         pull_url="${file//<branch>/${target_branch}}"
-        output_filepath="${file##*"${target_branch}"/}"
-        #if ! curl -sSfL "${file}" -o "${nvim_config_path}/init.lua"; then
-        #    printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
-        #    exit 3
-        #fi
-        echo "$pull_url"
-        echo "$output_filepath"
+        output_filepath=${file##*/src/}
+        if ! curl -sSfL "${pull_url}" --create-dirs --output "${nvim_config_path}{$output_filepath}"; then
+            printf "Downloading customization files to \`%s\`... Failed!\n" "${nvim_config_path}"
+            exit 3
+        fi
     done
 
     printf "Downloading customization files to \`%s\`... Done!\n" "${nvim_config_path}"
